In [115]:
import numpy as np

In [116]:
np.random.seed(101)
myList =np.random.randint(0,100,10)
myList

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [117]:
type(myList)

numpy.ndarray

In [118]:
arr2=np.random.randint(0,100,10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [123]:
myList.mean()

60.8

In [129]:
myList.reshape(10,1)

array([[95],
       [11],
       [81],
       [70],
       [63],
       [87],
       [75],
       [ 9],
       [77],
       [40]])

In [135]:
example =np.arange(0,100).reshape(10,10)

In [136]:
example

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
example[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])